spring.application.name=auth-service
server.port=8002
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:9999,optional:file:../.env[.properties],optional:file:../../.env[.properties]


brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
